# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15396af282cade370d5cfc81bf252f5e27e0e3f70febc719e48eab96bf5a126918c11f6da56fa104f85ff585a10b9c88423a7ad26b7cf89f80827f1dc73ac128

test:
  secret_key_base: 4067db405187aeabdf0d8e53e2f2b754f0c77427c5a1fde1ec466460db9f7e2ea9f4b1cbb4027241307b72511cd5f94049af8d68a50bfa76eef729c6db91a4a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
